name: FunctionalServerControl
version: '${project.version}'
main: by.alis.functionalservercontrol.spigot.FunctionalServerControl
api-version: 1.13
authors: [ ALis ]
description: Multifunctional control of the server and players
website: https://vk.com/alphatwo
softdepend: [Vault, LuckPerms, ProtocolLib, ViaVersion, ProtocolSupport]
commands:
  test:
  deviceinfo:
    aliases: [dinfo]
  kick:
  functionalservercontrol:
    aliases: [fsc, fscontrol]
  ban:
  tempban:
    aliases: [temporaryban]
  kickall:
  unban:
  unbanall:
  crazykick:
    aliases: [ckick]
  dupeip:
  cheatcheck:
    aliases: [ccheck]
  tempbanip:
    aliases: [temporarybanip]
  banip:
  mute:
  tempmute:
    aliases: [temporarymute]
  unmute:
  muteip:
  tempmuteip:
  unmuteall:
  getversion:
    aliases: [gv, getver]
  getclient:
    aliases: [gc, getc]
  getinfo:
    aliases: [getinformation, gi]
  banlist:
    aliases: [banslist]
  mutelist:
    aliases: [muteslist]
  clearchat:
    aliases: [cleanchat]
